version: '3.8'

services:
  app:
    build: .
    image: podcast-ad-remover
    restart: unless-stopped
    ports:
      - '8000:8000'
    volumes:
      - ./data:/data
      - .:/app
    environment:
      - GEMINI_API_KEY=
      - LOG_LEVEL=INFO
